### ISSUE TITLE
RFE: use symbol versioning in shared library

### ISSUE THREAD

**Issue by sharkcz** [opencryptoki/libica#3]
I would like to see libica to use symbol versioning for objects provided by the shared library. In combination with package management tools (eg. rpm and automatic Provides/Requires) it will avoid situations when older but same soname library will be installed, but application will require symbols from the latest release.

It's on my To-Do for some time ...

**Comment by p-steuer** [comment]
I opened a work-in-progress PR to work on this:
https://github.com/opencryptoki/libica/pull/4

**Comment by p-steuer** [comment]
Would the symbol versioning be considered an abi break (require a major version 4 release) ?

**Comment by sharkcz** [comment]
AFAIK adding the version information doesn't change the ABI in a incompatible way, so I would keep the soname.

**Comment by p-steuer** [comment]
Merged 3fefc3f8d284665a615eadbf3e8ae71dc06fe75a
