### ISSUE TITLE
FIPS integrity check fails

### ISSUE THREAD

**Issue by sharkcz** [opencryptoki/libica#45]
The FIPS integrity check introduced in commit 231bba3b fails, because it tries to work with the development symlink, not with the actual library. https://github.com/opencryptoki/libica/blob/master/src/fips.c#L309 is not right, it must be looking after `/usr/lib64/libica.so.3`

**Comment by sharkcz** [comment]
See also https://bugzilla.redhat.com/show_bug.cgi?id=1857130

**Comment by sharkcz** [comment]
https://github.com/opencryptoki/openssl-ibmca/commit/f4c9d610e39624be09ba4de36e29c60a478537e7 is fixing similar issue in ibmca

**Comment by hramrach** [comment]
How about using the full version?

The actual library file is named with full version, and this is what other libraries do:

ls -l usr/lib64/
total 244
lrwxrwxrwx 1 hramrach users     15 Aug 28 13:58 libica.so.3 -> libica.so.3.6.0
-rwxr-xr-x 1 hramrach users 248744 Aug 28 13:58 libica.so.3.6.0

--- libica-3.6.0/src/fips.c.orig	2020-08-27 10:54:28.587931890 +0200
+++ libica-3.6.0/src/fips.c	2020-08-27 11:09:34.392320988 +0200
@@ -302,7 +302,7 @@
 {
 	int rc;
 	char path[PATH_MAX];
-	const char *libname = "libica.so";
+	const char *libname = "libica.so." VERSION;
 	const char *symbolname = "ica_sha256";
 
 	rc = get_library_path(libname, symbolname, path, sizeof(path));

**Comment by sharkcz** [comment]
Hmm, using the full filename might be actually better in the FIPS context.

**Comment by hramrach** [comment]
https://github.com/opencryptoki/libica/pull/52

**Comment by hramrach** [comment]
This is actually completely bogus. The check already hashed libica.so.3 before this patch.
