### ISSUE TITLE
Modular multiplication implementation in s390_rsa.c

### ISSUE THREAD

**Issue by simo5** [opencryptoki/libica#47]
Starting at https://github.com/opencryptoki/libica/blob/524659f8e042aed45015e1aca930a3cfe5ffa628/src/s390_rsa.c#L300 there is a full set of functions implementing RSA's modular multiplication.
It is not clear to me if anything is using this inside libica (it is marked as deprecated with a comment), but this is the core of the RSA algorithm (cryptography).
If nothing is using it it should probably be removed.
If something is using it it should be converted instead to use OpenSSL's RSA (preferably via EVP interface) to execute the whole encryption or signature function required.

**Comment by simo5** [comment]
Note that this seem a public function exported in the header,
but a github search does not revela other callers in libica nor in opencryptoki/openssl-ibmca

**Comment by p-steuer** [comment]
src/include are internal header files. The public header is include/ica_api.h. All symbols the library exports are controlled via libica.map linker script. So the symbol is not visible to the outside and nothing can depend on it.

**Comment by p-steuer** [comment]
I see its not used internall either.. so the code can just be removed.

**Comment by p-steuer** [comment]
All key generation stuff maps to libcrypto's RSA_generate_key_ex.which is to be deprecated for the penssl 3.0.

The rest of the code looks like SW fallbacks for RSA implemented via libcrypto BIGNUMs. Should be possible to replace it by libcrypto calls.

**Comment by simo5** [comment]
rsa_mod_mul_sw() is not used, but the next one defined in the header file which is rsa_mod_expo_sw (rsa exposnentiation) is used in src/ica_api.c, however this one is only used in a construct like:
`rc = ica_fallbacks_enabled ? rsa_mod_expo_sw(&rb) : ENODEV;`

Sounds like it can simply be removed as well?

**Comment by p-steuer** [comment]
Its not an exported API, but as i said, those are the SW fallbacks which kick in if the crypto adapter fails for some reason and SW fallbacks are not disabled. I dont think it can be removed, it should be replaced by a libcrypto call with the minimum glue code possible

**Comment by simo5** [comment]
If it can't be removed it should definitely be replaced with libcrypto calls, because the implementation in s390_rsa.c also does not handle things like doing computations in constant time, so it is a liability.
At least my understandning is that openssl main has replaced the use of BN_mod_exp() with BN_mod_exp_mont_consttime() where it matters...

**Comment by p-steuer** [comment]
Yes, there has been quite some effort to make BN_ constant time. The rsa code clearly predates that though.

**Comment by simo5** [comment]
I am ok if you give a compile time option on what to do with them, so they can be disabled at build time but available for people compiling from source if they want to.

**Comment by jschmidb** [comment]
Fixed in libica 4.0.0: compile time option NO_SW_FALLBACKS is now the default. 
Closing.
