### ISSUE TITLE
HMAC is computed from built libica

### ISSUE THREAD

**Issue by sharkcz** [opencryptoki/libica#62]
The HMAC hash is computed from the libica in the build tree, but the runtime check is run against the installed libica and those 2 files are different. The runtime one has debuginfo stripped (and placed into a separate file), thus the hashes are different. I think that for computing the hashes a distro tooling must be used rather to create them during the "plain" build.

**Comment by sharkcz** [comment]
see for example https://src.fedoraproject.org/rpms/openssl/blob/rawhide/f/openssl.spec#_307

**Comment by jschmidb** [comment]
Hi Dan, yes it's true: when you build with fips and debug, the .so modules in src/.libs are different from the ones installed. My first idea was to simply create the hmac new in the install-data-hook, but it looks like the stripping of the debug info happens after make install is completely finished. Our setup is similar to what gnutls does. Do you have the same problem there?

**Comment by sharkcz** [comment]
The gnutls rpm package does the same thing as openssl above (modifies the "post-install" hook for rpmbuild), so libica will have to use the same mechanism. Looking at the gnutls [build.log](https://kojipkgs.fedoraproject.org//packages/gnutls/3.7.2/1.fc34/data/logs/x86_64/build.log) they create hmac during the build using the upstream provided rule and then recreate it using the rpmbuild hook. So you shouldn't be changing anything and I will update the rpm package. The only update that would be useful is to provide a wrapper over the openssl command to create the hmac, both openssl and gnutls seems to have one. Or we could require the hmaccalc package to be installed, which is what the kernel does.

**Comment by jschmidb** [comment]
> The only update that would be useful is to provide a wrapper over the openssl command to create the hmac, both openssl and gnutls seems to have one. Or we could require the hmaccalc package to be installed, which is what the kernel does.

Ok good, I will put this on our list. Thanks for the hint.

**Comment by jschmidb** [comment]
Agreed with Dan to close.
