### ISSUE TITLE
Encounter an error when make to install the libica library

### ISSUE THREAD

**Issue by penny56** [opencryptoki/libica#70]
Hi,

I got this error when I try to run the 'make' command to install the libica library, here is the log showing in my terminal, could you help to take a look? Thanks~

`libtool: compile:  gcc -DPACKAGE_NAME=\"libica\" -DPACKAGE_TARNAME=\"libica\" -DPACKAGE_VERSION=\"3.8.0\" "-DPACKAGE_STRING=\"libica 3.8.0\"" -DPACKAGE_BUGREPORT=\"https://github.com/opencryptoki/libica/issues\" -DPACKAGE_URL=\"https://github.com/opencryptoki/libica\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -D__EXTENSIONS__=1 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D_TANDEM_SOURCE=1 -DHAVE_FCNTL_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STDDEF_H=1 -DHAVE_STDINT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_STRINGS_H=1 -DHAVE_SYS_FILE_H=1 -DHAVE_SYS_IOCTL_H=1 -DHAVE_SYS_TIME_H=1 -DHAVE_SYSLOG_H=1 -DHAVE_UNISTD_H=1 -DHAVE_STDLIB_H=1 -DHAVE_MALLOC=1 -DHAVE_STDLIB_H=1 -DHAVE_UNISTD_H=1 -DHAVE_SYS_PARAM_H=1 -DHAVE_GETPAGESIZE=1 -DHAVE_MMAP=1 -DHAVE_BZERO=1 -DHAVE_FTRUNCATE=1 -DHAVE_GETTIMEOFDAY=1 -DHAVE_MEMCHR=1 -DHAVE_MEMSET=1 -DHAVE_MUNMAP=1 -DHAVE_STRCASECMP=1 -DHAVE_STRERROR=1 -DHAVE_STRSTR=1 -DHAVE_STRTOL=1 -DHAVE_SETENV=1 -DHAVE_STRTOULL=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DPACKAGE=\"libica\" -DVERSION=\"3.8.0\" -I. -Wall -Wextra -mzarch -DICA_FIPS -O3 -D_FORTIFY_SOURCE=2 -I./include -I./../include -fvisibility=hidden -pthread -DLIBNAME=\"libica\" -MT libica_la-ica_api.lo -MD -MP -MF .deps/libica_la-ica_api.Tpo -c ica_api.c  -fPIC -DPIC -o .libs/libica_la-ica_api.o
../libtool: line 1762: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory
In file included from ica_api.c:34:
./include/s390_rsa.h:17:10: fatal error: openssl/bn.h: No such file or directory
 #include <openssl/bn.h>
          ^~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:913: libica_la-ica_api.lo] Error 1
make[1]: Leaving directory '/root/libica-3.8.0/src'
make: *** [Makefile:439: all-recursive] Error 1`

The release I download is libica-3.8.0.tar.gz
And the environment is RHEL8.1 on s390x LinuxONE III
openssl version is:
[root@rhel81 ~]# openssl version
OpenSSL 1.1.1c FIPS  28 May 2019

Please feel free to let me know for any more information, thanks

**Comment by penny56** [comment]
![image](https://user-images.githubusercontent.com/13374916/128284318-31264ac1-cc13-469c-ab3b-799ff0e1613e.png)
Let me upload a screen shot for the indent was messed up.

**Comment by jschmidb** [comment]
Hello .... just to check the basics: do you have openssl-devel installed? The openssl H-files should be located in /usr/include/openssl. Can you check if the files are there?

**Comment by penny56** [comment]
Hi Joerg, thank you for the reply, the answer is no, the openssl file not there.

[root@rhel81 include]# pwd
/usr/include
[root@rhel81 include]# cat openssl
cat: openssl: No such file or directory

**Comment by jschmidb** [comment]
Then it looks like the openssl-devel package is not installed. This installs the openssl include files. Try a 
yum install openssl-devel

**Comment by ifranzki** [comment]
Maybe you should add a dependency check to configure then?

**Comment by penny56** [comment]
Hi Joerg, Ingo,

Thanks for the help! I installed the CCA host lib and then stop/start the partition (aka LPAR), thinks looks good now~ Close this issue.

Thanks.
